name: "Docker: backend Images"

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Docker Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Branch Names
      uses: tj-actions/branch-names@v5.4

    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0

      with:
        context: .
        push: true
        pull: true
        tags: spdiam/cenit:fronted-v2-${{ github.run_attempt }}
